name: CI Workflow Luma Application

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress Run
        uses: cypress-io/github-action@v5

      - name: Install Dependencies
        run: npm install

      - name: Start the Server
        run: npm start &

         # Step 5: Wait for the server to be ready


      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        with:
         record: false # Set to true if using Cypress Dashboard
         start: npm start

