name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Install Cypress
    - name: Install Cypress
      run: npm install cypress --save-dev

    # Step 5: Set up Cypress binary
    - name: Verify Cypress
      run: npx cypress verify

    # Step 6: Run Cypress tests
    - name: Run Cypress Tests
      run: npx cypress run